apiVersion: apps/v1
kind: Deployment
metadata:
  name: cache-service
  labels:
    app: cache-service
spec:
  selector:
    matchLabels:
      app: cache-service
  template:
    metadata:
      labels:
        app: cache-service
    spec:
      containers:
        - name: cache-service
          image: geoffreyanto12/cache-service:latest
          resources:
            limits:
              memory: "256Mi"
              cpu: "1"
          envFrom:
            - configMapRef:
                name: cache-service-configmap
          ports:
          - containerPort: 50052

---

kind: Service
apiVersion: v1
metadata:
  name:  cache-service
spec:
  selector:
    app:  cache-service
  type:  LoadBalancer
  ports:
  - name:  http
    port:  50052
    targetPort:  50052