apiVersion: apps/v1
kind: Deployment
metadata:
  name: email-service
  labels:
    app: email-service
spec:
  selector:
    matchLabels:
      app: email-service
  template:
    metadata:
      labels:
        app: email-service
    spec:
      containers:
        - name: email-service
          image: geoffreyanto12/email-service:latest
          resources:
            limits:
              memory: "256Mi"
              cpu: "1"
          envFrom:
            - secretRef:
                name: email-service-secret
          ports:
          - containerPort: 50051

---

apiVersion: v1
kind: Service
metadata:
  name: email-service
spec:
  selector:
    app: email-service
  ports:
    - protocol: TCP
      port: 50051
      targetPort: 50051