apiVersion: v1
kind: Secret
metadata:
  name: email-service-secret
  labels:
    app: email-service
data:
  EMAIL_ADDRESS: ZW1haWwtYWRkcmVzcw==
  EMAIL_PASSWORD: ZW1haWwtcGFzc3dvcmQ=
  SMTP_HOST: c210cC5nbWFpbC5jb20=
  SMTP_PORT: NTg3
  PORT: NTAwNTE=