version: "3"
services:
  proxy:
    build:
      context: ./proxy
      dockerfile: Dockerfile
    ports:
      - "80:80"
    restart: always
    networks:
      - eventriest_network

  api-server:
    build:
      context: ./api-server
      dockerfile: Dockerfile
    restart: always
    environment:
      - PORT=3000
    networks:
      - eventriest_network
    scale: 2
    depends_on:
      - proxy

  email-service:
    build:
      context: ./email-service
      dockerfile: Dockerfile
    restart: always
    env_file:
      - ./.env
    ports:
      - "3002:3002"

networks:
  eventriest_network:
    driver: bridge
