version: "3"
services:
  proxy:
    build:
      context: ./proxy
      dockerfile: Dockerfile
    ports:
      - "80:80"
    restart: always
    networks:
      - eventriest_network

  api-server:
    build:
      context: ./api-server
      dockerfile: Dockerfile
    restart: always
    env_file:
      - ./api_server.env
    networks:
      - eventriest_network
    scale: 1
    depends_on:
      - proxy

  email-service:
    build:
      context: ./email-service
      dockerfile: Dockerfile
    restart: always
    env_file:
      - ./email_service.env
    networks:
      - eventriest_network
    ports:
      - "50051:50051"

  database:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /pg-data
    ports:
      - "5432:5432"
    volumes:
      - pg-data:/pg-data
    networks:
      - eventriest_network

  redis-db:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    networks:
      - eventriest_network

networks:
  eventriest_network:
    driver: bridge

volumes:
  pg-data:
