apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.ApiServer.Secret.Name }}
type: Opaque
data:
  PORT: {{ .Values.ApiServer.Deployment.ContainerPort | toString | b64enc }}
  DATABASE_URL: {{ printf "postgres://%s:%s@%s:%.0f/%s" .Values.Postgres.ConfigMap.User .Values.Postgres.ConfigMap.Password .Values.Postgres.Service.Name .Values.Postgres.Service.Port  .Values.Postgres.ConfigMap.DB | b64enc }}
  REDIS_URL: {{ printf "redis://%s:%.0f" .Values.Redis.Service.Name .Values.Redis.Service.Port | b64enc }}
  EMAIL_SERVICE_ADDRESS: {{ printf "%s:%.0f" .Values.EmailService.Service.Name .Values.EmailService.Service.Port | b64enc }}
