apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.EmailService.Secret.Name }}
  labels:
    app: {{ .Values.EmailService.Deployment.Name }}
data:
  EMAIL_ADDRESS: ZW1haWwtYWRkcmVzcw==
  EMAIL_PASSWORD: ZW1haWwtcGFzc3dvcmQ=
  SMTP_HOST: c210cC5nbWFpbC5jb20=
  SMTP_PORT: NTg3
  PORT: {{ .Values.EmailService.Deployment.ContainerPort | toString | b64enc }}
